version: "3.9"

services: 
    flak_app:
        build: .
        container_name: flak_app
        command: python3 app.py
        volumes: 
          -   .:/code
        ports: 
          -  "5000:5000"
        environment:
          - DEBUG=True
        depends_on: 
          - postgres_db
        restart: always
    postgres_db:
        image: postgres
        container_name: postgres_db
        expose:
          - "5432"
        environment: 
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        volumes: 
          - pgdata:/var/lib/postgresql/data/
        restart: always
volumes: 
    pgdata: